run:
  dir: ${paths.experiments_dir}/${command_name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
sweep:
  dir: ./logs/tfh_train_hparams_search/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}

output_subdir: 'yamls'
