model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  monitor: ???
  mode: ???
  dirpath: null
  filename: null
  verbose: false
  save_last: true
  save_top_k: 10
  auto_insert_metric_name: true
  save_weights_only: false
  every_n_train_steps: null
  train_time_interval: null
  every_n_epochs: 1
  save_on_train_epoch_end: null
